#!/usr/bin/env ruby

$LOAD_PATH.unshift      File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))

# This program trundles through one or more disk-based silos and does md5 and sha1 checksums,
# adding them to thea SiloDB/SiloTape  database.

# TODO: extend DB to allow recording current size, as well

require 'datyl/logger'
require 'datyl/reporter'
require 'digest/md5'
require 'digest/sha1'
require 'optparse'
require 'store/silodb'
require 'store/utils'

def get_options args
  conf = OpenStruct.new(:hostname => nil, :syslog_facility => nil, :db_config_key => nil, :db_config_file => '/opt/fda/etc/db.yml', :fresh_enough => 7, :pid_directory => nil)

  opts = OptionParser.new do |opts|

    opts.banner = "Usage: #{$0.sub(%r{.*/}, '')} [ --options ] [ /silo/001 .. ]\n" +
                  "       without an explicit list of disk silos, do checks on all of them."

    opts.on("--hostname HOST",   String, "Required, the name of the host this silo is associated with (usually a virtual host)") do |hostname|
      conf.hostname = hostname.downcase
    end

    opts.on("--fresh-enough DAYS",  Integer, "If a fixity check has been done in less than the supplied DAYS, don't do another (defaults to #{conf.fresh_enough})") do |days|
      conf.fresh_enough = days
    end

    opts.on("--pid-directory PATH", String, "Optionally, a directory for storing this scripts PID for external moitoring agents, such as xymon") do |path|
      conf.pid_directory = path
    end
    
    opts.on("--db-config-file PATH",  String, "A database yaml configuration file, defaults to #{conf.db_config_file}") do |path|
      conf.db_config_file = path
    end
    
    opts.on("--db-config-key KEY",  String, "The key for the database information in the database yaml configuration file #{conf.db_config_file}") do |key|
      conf.db_config_key = key
    end

    opts.on("--syslog-facility FACILITY",  String, "The facility in syslog to log to, otherwise log to STDERR") do |facility|
      conf.syslog_facility = facility
    end
  end
  opts.parse!(args) 
  raise "No hostname provided"  unless conf.hostname
  raise "No key into the DB configuration file (#{conf.db_config_file}) provided" unless conf.db_config_key
  raise "Default yaml file #{conf.db_config_file} not found" unless File.exists? conf.db_config_file
  
rescue => e
  STDERR.puts e, opts
  exit 1
else
  return conf
end

def setup config
  Kernel.trap('INT')  { Process.exit! 1 }

  $0 = 'disk-fixity'

  Logger.setup('DiskFixity', config.hostname)

  if config.syslog_facility
    Logger.facility  = config.syslog_facility 
  else
    Logger.stderr   
  end

  if config.pid_directory
    pid_path = StoreUtils.pid_file(config.pid_directory)
    raise "PID file #{pid_path} exists. This indicates another copy of this script is running or has previously crashed; exiting"   if File.exists? pid_path
    File.open(pid_path, 'w') { |file|  file.puts $$ }
  end

  Reporter.max_lines_to_write = 100    # each report will have at most these lines, though everything will go to syslog

  begin
    Store::SiloDB.setup config.db_config_file, config.db_config_key
  rescue => e
    Logger.err e.message
    exit
  end

  Kernel.trap('PIPE') { exit }
end


def teardown config
  if config.pid_directory
    pid_path = StoreUtils.pid_file(config.pid_directory)
    File.delete pid_path if File.exists? pid_path and File.writable? pid_path
  end
end


# order the disk silos by oldest complete fixity time, latest first; if silos have been specified on the command line, restrict our list to those

def select_silos config, reporter
  silos = Store::DB::SiloRecord.list(config.hostname).select{ |s| s.state == :disk_master }.map{ |rec| Store::SiloDB.new(rec.hostname, rec.filesystem) }

  candidates = ARGV.map { |s| s.sub(%r{/+$}, '') }

  silos = silos.select { |s| candidates.include? s.filesystem } unless candidates.empty?
  silos = silos.select{ |s| s.oldest_fixity }.sort{ |a,b| a.oldest_fixity <=> b.oldest_fixity }

  return silos
rescue => e
  reporter.error "Failed selecting the list of silos to process:"
  reporter.error "#{e.class} #{e.message}, backtrace follows:"
  e.backtrace.each { |line| reporter.error "   #{lin}" }
  
  reporter.write
  exit
end



config = get_options(ARGV)
setup(config)

reporter = Reporter.new('Fixity Disk Checks')
silos    = select_silos(config, reporter)

if silos.empty?                                                   # TODO: prettier output here
  reporter.warn "There were no silos available to process"
  reporter.warn "Configuration options: #{config.inspect}"
  reporter.warn "Silos specified on the command line: #{ARGV * ', '}" unless ARGV.empty?
end
  

silos.each do |silo|

  reporter.info 
  reporter.info "Beginning bulk fixity update for silo #{silo} " + DateTime.now.strftime('Starting %A, %B %d, %Y at %r')

  silo.each_package_record do |package|
    next if (DateTime.now - package.latest_timestamp) <  config.fresh_enough
    begin
      md5  = Digest::MD5.new
      sha1 = Digest::SHA1.new
      silo.get(package.name) do |buff|
        md5  << buff
        sha1 << buff
      end
      md5   = md5.hexdigest
      sha1  = sha1.hexdigest
    rescue => e    
      reporter.err "Unexpected during fixity checking on silo #{silo} (on package #{package}): #{e.message}."
    else
      silo.fixity(package.name, :md5 => md5, :sha1 => sha1)
      errors = []
      errors.push "md5 mismatch - expected #{silo.md5(package.name)} but got #{md5}"    if (md5  != silo.md5(package.name))
      errors.push "sha1 mismatch - expected #{silo.sha1(package.name)} but got #{sha1}" if (sha1 != silo.sha1(package.name))

      if not errors.empty?
        reporter.err "Fixity failure for package #{package.name} on silo #{silo}:"
        errors.each { |line|  reporter.err "   #{line}" }
      end
    end
  end  
end

reporter.write
